name: IMMOXL
description: A real estate app.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.4.0+9
  cupertino_icons: ^0.1.2
  cupertino_tabbar: ^1.0.1
  flutter_svg: any
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: b41932100ba8af15326560384d6667b4bd087c35
  location: any
  url_launcher: 5.4.5
  carousel_pro: any
  photo_view: 0.9.2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  equatable: ^1.1.1
  email_validator: any
  flushbar: any
  flutter_spinkit: 4.1.2+1
  shared_preferences: ^0.4.3
  geolocator: ^5.3.1
  latlong: ^0.6.1
  auto_size_text: ^2.1.0
  image_picker: 0.6.6+1
  firebase_storage: ^3.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/langs/en.json
    - assets/langs/nl.json

  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans/PTSans-Bold.ttf
        - asset: fonts/PTSans/PTSans-BoldItalic.ttf
        - asset: fonts/PTSans/PTSans-Italic.ttf
        - asset: fonts/PTSans/PTSans-Regular.ttf
    - family: TheNextFont
      fonts:
        - asset: fonts/TheNextFont/TheNextFont.ttf


